{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7Amplify18RecoverySuggestiona","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","text":"RecoverySuggestion"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/recoverySuggestion","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/AmplifyError-Implementations"]]},"abstract":[{"text":"A localized message describing how one might recover from the failure.","type":"text"}],"metadata":{"modules":[{"name":"Amplify"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona"}],"title":"recoverySuggestion","externalID":"s:7Amplify9AuthErrorO18recoverySuggestionSSvp","extendedModule":"Amplify","role":"symbol","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/autherror\/recoverysuggestion"]}],"kind":"symbol","references":{"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/recoverySuggestion":{"url":"\/documentation\/amplify\/autherror\/recoverysuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RecoverySuggestion","preciseIdentifier":"s:7Amplify18RecoverySuggestiona","kind":"typeIdentifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/recoverySuggestion","abstract":[{"text":"A localized message describing how one might recover from the failure.","type":"text"}],"role":"symbol","title":"recoverySuggestion","type":"topic","kind":"symbol"},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError/AmplifyError-Implementations":{"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError\/AmplifyError-Implementations","abstract":[],"title":"AmplifyError Implementations","kind":"article","role":"collectionGroup","type":"topic","url":"\/documentation\/amplify\/autherror\/amplifyerror-implementations"},"doc://amplify-swift.Amplify/documentation/Amplify/RecoverySuggestion":{"url":"\/documentation\/amplify\/recoverysuggestion","title":"RecoverySuggestion","type":"topic","abstract":[{"type":"text","text":"See: "},{"identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion","type":"reference","isActive":true}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/RecoverySuggestion","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecoverySuggestion","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"RecoverySuggestion","kind":"identifier"}]},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/AuthError":{"navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"kind":"symbol","role":"symbol","url":"\/documentation\/amplify\/autherror","title":"AuthError","type":"topic","abstract":[{"type":"text","text":"Amplify error raised in the Auth category."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthError","kind":"identifier"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AuthError"},"x-source-tag://AmplifyError.recoverySuggestion":{"title":"AmplifyError.recoverySuggestion","titleInlineContent":[{"text":"AmplifyError.recoverySuggestion","type":"text"}],"type":"link","url":"x-source-tag:\/\/AmplifyError.recoverySuggestion","identifier":"x-source-tag:\/\/AmplifyError.recoverySuggestion"}}}