{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError\/underlyingError"},"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","required":true,"externalID":"s:7Amplify0A5ErrorP010underlyingB0s0B0_pSgvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"underlyingError","kind":"identifier"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"underlyingError","modules":[{"name":"Amplify"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/amplify\/amplifyerror\/underlyingerror"]}],"abstract":[{"type":"text","text":"The underlying error that caused the error condition"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"underlyingError","kind":"identifier"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError":{"navigatorTitle":[{"kind":"identifier","text":"AmplifyError"}],"role":"symbol","title":"AmplifyError","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError","abstract":[{"type":"text","text":"Amplifyâ€™s philosophy is to expose friendly error messages to the customer that assist with debugging."},{"type":"text","text":" "},{"type":"text","text":"Therefore, failable APIs are declared to return error results with Amplify errors, which require"},{"type":"text","text":" "},{"type":"text","text":"recovery suggestions and error messages."}],"kind":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AmplifyError"}],"url":"\/documentation\/amplify\/amplifyerror"},"doc://amplify-swift.Amplify/documentation/Amplify/AmplifyError/underlyingError":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/AmplifyError\/underlyingError","required":true,"abstract":[{"type":"text","text":"The underlying error that caused the error condition"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"underlyingError"},{"kind":"text","text":": "},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"url":"\/documentation\/amplify\/amplifyerror\/underlyingerror","title":"underlyingError"}}}