{"hierarchy":{"paths":[["doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError","doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError\/AmplifyError-Implementations"]]},"metadata":{"role":"symbol","title":"underlyingError","roleHeading":"Instance Property","extendedModule":"Amplify","modules":[{"name":"Amplify"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"underlyingError"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":"?","kind":"text"}],"externalID":"s:7Amplify16PredictionsErrorO010underlyingC0s0C0_pSgvp"},"identifier":{"url":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError\/underlyingError","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"The underlying error that caused the error condition"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"underlyingError","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/amplify\/predictionserror\/underlyingerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://amplify-swift.Amplify/documentation/Amplify/PredictionsError/underlyingError":{"title":"underlyingError","abstract":[{"type":"text","text":"The underlying error that caused the error condition"}],"type":"topic","url":"\/documentation\/amplify\/predictionserror\/underlyingerror","role":"symbol","kind":"symbol","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError\/underlyingError","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"underlyingError","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":"?","kind":"text"}]},"doc://amplify-swift.Amplify/documentation/Amplify/PredictionsError/AmplifyError-Implementations":{"type":"topic","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError\/AmplifyError-Implementations","url":"\/documentation\/amplify\/predictionserror\/amplifyerror-implementations","abstract":[],"role":"collectionGroup","title":"AmplifyError Implementations","kind":"article"},"doc://amplify-swift.Amplify/documentation/Amplify/PredictionsError":{"title":"PredictionsError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PredictionsError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PredictionsError"}],"type":"topic","abstract":[{"type":"text","text":"Error occured while using Prediction category"}],"identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify\/PredictionsError","url":"\/documentation\/amplify\/predictionserror"},"doc://amplify-swift.Amplify/documentation/Amplify":{"url":"\/documentation\/amplify","type":"topic","title":"Amplify","role":"collection","identifier":"doc:\/\/amplify-swift.Amplify\/documentation\/Amplify","kind":"symbol","abstract":[]}}}